/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackToHome: typeof import('./src/components/BackToHome.vue')['default']
    Default: typeof import('./src/layouts/default.vue')['default']
    GradientAnimation: typeof import('./src/components/GradientAnimation.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NutActionSheet: typeof import('nutui-uniapp/components/actionsheet/actionsheet.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutConfigProvider: typeof import('nutui-uniapp/components/configprovider/configprovider.vue')['default']
    NutDialog: typeof import('nutui-uniapp/components/dialog/dialog.vue')['default']
    NutLoadingPage: typeof import('nutui-uniapp/components/loadingpage/loadingpage.vue')['default']
    NutNotify: typeof import('nutui-uniapp/components/notify/notify.vue')['default']
    NutToast: typeof import('nutui-uniapp/components/toast/toast.vue')['default']
    NutUiDemo: typeof import('./src/components/NutUiDemo.vue')['default']
    NutUiProvider: typeof import('./src/components/NutUiProvider.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    ToggleDarkMode: typeof import('./src/components/ToggleDarkMode.vue')['default']
    ToggleLanguage: typeof import('./src/components/ToggleLanguage.vue')['default']
    VinAvatar: typeof import('@vingogo/uni-ui/lib/components/avatar/index.vue')['default']
    VinButton: typeof import('@vingogo/uni-ui/lib/components/button/index.vue')['default']
    VinCalendarItem: typeof import('@vingogo/uni-ui/lib/components/calendar-item/index.vue')['default']
    VinCascaderItem: typeof import('@vingogo/uni-ui/lib/components/cascader-item/index.vue')['default']
    VinCell: typeof import('@vingogo/uni-ui/lib/components/cell/index.vue')['default']
    VinCellGroup: typeof import('@vingogo/uni-ui/lib/components/cell-group/index.vue')['default']
    VinCommentBottom: typeof import('@vingogo/uni-ui/lib/components/comment-bottom/index.vue')['default']
    VinCommentHeader: typeof import('@vingogo/uni-ui/lib/components/comment-header/index.vue')['default']
    VinCommentImages: typeof import('@vingogo/uni-ui/lib/components/comment-images/index.vue')['default']
    VinIcon: typeof import('@vingogo/uni-ui/lib/components/icon/index.vue')['default']
    VinOverlay: typeof import('@vingogo/uni-ui/lib/components/overlay/index.vue')['default']
    VinPopup: typeof import('@vingogo/uni-ui/lib/components/popup/index.vue')['default']
    VinPrice: typeof import('@vingogo/uni-ui/lib/components/price/index.vue')['default']
    VinProgress: typeof import('@vingogo/uni-ui/lib/components/progress/index.vue')['default']
    VinRate: typeof import('@vingogo/uni-ui/lib/components/rate/index.vue')['default']
    VinTabpane: typeof import('@vingogo/uni-ui/lib/components/tabpane/index.vue')['default']
    VinTabs: typeof import('@vingogo/uni-ui/lib/components/tabs/index.vue')['default']
    VinTag: typeof import('@vingogo/uni-ui/lib/components/tag/index.vue')['default']
    VinTransition: typeof import('@vingogo/uni-ui/lib/components/transition/index.vue')['default']
    VinUiDemo: typeof import('./src/components/VinUiDemo.vue')['default']
    VinUiProvider: typeof import('./src/components/VinUiProvider.vue')['default']
    WdActionSheet: typeof import('wot-design-uni/components/wd-action-sheet/wd-action-sheet.vue')['default']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['default']
    WdConfigProvider: typeof import('wot-design-uni/components/wd-config-provider/wd-config-provider.vue')['default']
    WdIcon: typeof import('wot-design-uni/components/wd-icon/wd-icon.vue')['default']
    WdInput: typeof import('wot-design-uni/components/wd-input/wd-input.vue')['default']
    WdLoading: typeof import('wot-design-uni/components/wd-loading/wd-loading.vue')['default']
    WdMessageBox: typeof import('wot-design-uni/components/wd-message-box/wd-message-box.vue')['default']
    WdNotify: typeof import('wot-design-uni/components/wd-notify/wd-notify.vue')['default']
    WdOverlay: typeof import('wot-design-uni/components/wd-overlay/wd-overlay.vue')['default']
    WdPopup: typeof import('wot-design-uni/components/wd-popup/wd-popup.vue')['default']
    WdToast: typeof import('wot-design-uni/components/wd-toast/wd-toast.vue')['default']
    WdTransition: typeof import('wot-design-uni/components/wd-transition/wd-transition.vue')['default']
    WdUiDemo: typeof import('./src/components/WdUiDemo.vue')['default']
    WdUiProvider: typeof import('./src/components/WdUiProvider.vue')['default']
  }
}
