/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Default: typeof import('./src/layouts/default.vue')['default']
    DefaultMenu: typeof import('./src/components/DefaultMenu.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutConfigProvider: typeof import('nutui-uniapp/components/configprovider/configprovider.vue')['default']
    NutDialog: typeof import('nutui-uniapp/components/dialog/dialog.vue')['default']
    NutLoadingPage: typeof import('nutui-uniapp/components/loadingpage/loadingpage.vue')['default']
    NutNotify: typeof import('nutui-uniapp/components/notify/notify.vue')['default']
    NutToast: typeof import('nutui-uniapp/components/toast/toast.vue')['default']
    Page: typeof import('./src/layouts/page.vue')['default']
    VinButton: typeof import('@vingogo/uni-ui/lib/components/button/index.vue')['default']
    VinIcon: typeof import('@vingogo/uni-ui/lib/components/icon/index.vue')['default']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['default']
    WdIcon: typeof import('wot-design-uni/components/wd-icon/wd-icon.vue')['default']
  }
}
