// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./../layouts/DefaultLayout.vue')['default']
    DefaultMenu: typeof import('./../components/DefaultMenu.vue')['default']
    RouterEntry: typeof import('./../components/RouterEntry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
